apiVersion: v2
name: l2scan-stack-ce
description: A Helm chart for Kubernetes to deploy L2Scan Stack CE
type: application
version: 0.1.2
appVersion: "0.1.2"
keywords:
  - blockchain
  - explorer
  - l2scan
  - indexer
home: https://github.com/unifralabs/l2scan-stack-ce
sources:
  - https://github.com/unifralabs/l2scan-ce
  - https://github.com/unifralabs/l2scan-indexer-ce
maintainers:
  - name: L2Scan Team
    email: team@l2scan.com
dependencies:
  - name: postgresql
    version: "15.5.38"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
    alias: l2scan-postgresql
  - name: redis
    version: "20.3.0"  
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
    alias: l2scan-redis