apiVersion: v1
kind: Service
metadata:
  name: {{ include "l2scan-stack.fullname" . }}-verifier
  labels:
    {{- include "l2scan-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: verifier
spec:
  type: {{ .Values.verifier.service.type }}
  ports:
    - port: {{ .Values.verifier.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.verifier.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "l2scan-stack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: verifier 