{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "l2scan-stack.fullname" . }}-frontend
  labels:
    {{- include "l2scan-stack.frontend.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "l2scan-stack.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "l2scan-stack.frontend.selectorLabels" . | nindent 8 }}
      {{- with .Values.commonAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "l2scan-stack.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.frontend.securityContext | nindent 8 }}
      {{- if .Values.frontend.initContainer.enabled }}
      initContainers:
        - name: db-migrate
          image: {{ .Values.frontend.initContainer.image }}:{{ .Values.frontend.initContainer.tag }}
          imagePullPolicy: {{ .Values.frontend.initContainer.pullPolicy | default "IfNotPresent" }}
          env:
            - name: DATABASE_URL
              value: {{ include "l2scan-stack.postgresql.url" . | quote }}
            - name: NODE_ENV
              value: {{ .Values.frontend.initContainer.nodeEnv | default "production" | quote }}
          {{- with .Values.frontend.initContainer.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- end }}
      containers:
        - name: frontend
          image: {{ include "l2scan-stack.frontend.image" . }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.targetPort }}
              protocol: TCP
          env:
            - name: DATABASE_URL
              value: {{ include "l2scan-stack.postgresql.url" . | quote }}
            - name: REDIS_URL  
              value: {{ include "l2scan-stack.redis.url" . | quote }}
            - name: VERIFICATION_URL
              value: {{ include "l2scan-stack.verifier.url" . | quote }}
            {{- range $key, $value := .Values.frontend.env }}
            {{- if and $value (ne $key "DATABASE_URL") (ne $key "REDIS_URL") (ne $key "VERIFICATION_URL") }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          {{- with .Values.frontend.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.frontend.healthCheck.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.frontend.healthCheck.path }}
              port: http
            initialDelaySeconds: {{ .Values.frontend.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.healthCheck.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.frontend.healthCheck.path }}
              port: http
            initialDelaySeconds: {{ .Values.frontend.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.healthCheck.periodSeconds }}
          {{- end }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          {{- if .Values.frontend.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: /app/data
          {{- end }}
      {{- if .Values.frontend.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "l2scan-stack.fullname" . }}-frontend-data
      {{- end }}
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}