name: Release Helm Chart

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  release:
    types: [published]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - name: Add Helm repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: Update Chart version
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          # Extract version from tag (remove 'v' prefix)
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Updating chart version to $VERSION"
          
          # Update Chart.yaml
          sed -i "s/^version:.*/version: $VERSION/" helm-chart/Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: \"$VERSION\"/" helm-chart/Chart.yaml
          
          # Show the changes
          echo "Updated Chart.yaml:"
          cat helm-chart/Chart.yaml

      - name: Clean and update dependencies
        run: |
          cd helm-chart
          rm -rf charts/ Chart.lock
          helm dependency update

      - name: Lint Helm chart
        run: |
          helm lint helm-chart

      - name: Package Helm chart
        run: |
          mkdir -p .cr-release-packages
          helm package helm-chart --destination .cr-release-packages

      - name: Install chart-releaser
        run: |
          curl -sSLo cr.tar.gz "https://github.com/helm/chart-releaser/releases/download/v1.6.0/chart-releaser_1.6.0_linux_amd64.tar.gz"
          tar -xzf cr.tar.gz
          sudo mv cr /usr/local/bin/cr

      - name: Upload chart to GitHub Releases
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          cr upload \
            --owner "${{ github.repository_owner }}" \
            --git-repo "${{ github.event.repository.name }}" \
            --token "${{ secrets.GITHUB_TOKEN }}" \
            --commit $(git rev-parse HEAD)

      - name: Update Helm repository index
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          cr index \
            --owner "${{ github.repository_owner }}" \
            --git-repo "${{ github.event.repository.name }}" \
            --token "${{ secrets.GITHUB_TOKEN }}" \
            --pages-branch gh-pages \
            --push

 